version: '3.8' 

services:
  app:
    container_name: bank_app
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: mongodb://bank_mongodb:27017/bank_db?replicaSet=rs0
      PORT: 5000
    depends_on:
      db:
        condition: service_started
    command: npm start
    networks:
      - bank-network 

  frontend:
    container_name: bank_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:5173"
    environment:
      VITE_API_BASE: http://bank_app:5000/bank_app/api/v1 
    volumes:
      - ${PWD}/frontend:/app
      - /app/node_modules
    depends_on:
          app:
            condition: service_started
    command: sh -c "npm install && npm run build && npm run preview -- --port 5173 --host 0.0.0.0"
    networks:
      - bank-network 

  db:
    container_name: bank_mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    command: ["--replSet", "rs0"]
    volumes:
      - mongodb_data:/data/db
    networks:
      - bank-network 

volumes:
  mongodb_data:

networks:
  bank-network:
    driver: bridge